---
- name: Docker のリポジトリのキーを追加
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Docker のリポジトリを追加
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main'

- name: docker-engine のインストール
  apt: name=docker-engine state=present update_cache=yes

- name: docker-compose のインストール
  get_url: url=https://github.com/docker/compose/releases/download/1.7.1/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0755

- name: Docker を有効化 & 起動
  service: name=docker state=started enabled=yes
